site_name: Material Demo

theme:
  name: material 
  logo: images\demo_logo.png
  favicon: images\demo_logo.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: deep orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - blog

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://www.akmmusai.pro/"  target="_blank" rel="noopener">Akmmus AI</a>

nav:
  - 'Artificial Intelligence': 
      - '🧱 Introduction 🧱': 
          - Introduction/index.md  
          - 'AI': 'Introduction/AI.md'
          - 'Discriminative AI' : 'Introduction/Discriminative AI.md'
          - 'Generative AI' : 'Introduction/Generative AI.md'

  - 'Deep Learning':
     - 'Foundations':
          - '🔽 Activation Functions 🔽':
              - 'Introduction': 'Deep Learning/Activation Function.md'
              - 'Sigmoid': 'Deep Learning/Sigmoid.md'
              - 'Softmax': 'Deep Learning/Softmax.md'